apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-service-forgethefuture
  annotations:
    kubernetes.io/ingress.class: "gce"
    kubernetes.io/ingress.global-static-ip-name: "ingress-webapps" # Static IP
    networking.gke.io/managed-certificates: managed-cert-forgethefuture # Managed Certificate
    
spec:
  rules:
  - http:
      paths:
        - path: "/*"
          pathType: ImplementationSpecific
          backend:
            service:
              name: forgefuture
              port:
                number: 5000